language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn
  - gatsby build --prefix-links && gh-pages -d public -o live -b master -r "https://${GH_TOKEN}@github.com/lukeoliff/lukeoliff.github.io.git"
